### ISSUE TITLE
Add BufferFile.Size() int64

### ISSUE THREAD

**Issue by FiloSottile** [crawshaw/iox#1]
I would love to use BufferFile to stage downloads I don't know the size of before copying them into SQLite blobs, but currently I still have to keep track of their size manually (while with os.File I'd use Stat).

**Comment by crawshaw** [comment]
Are you looking for `BufferFile.Len()`?

This is equivalent to `n, _ := bf.Seek(0, os.SEEK_END)`. I added it to avoid the underlying syscall on large buffers.

**Comment by FiloSottile** [comment]
I am, but I don’t see it in the godoc?

I admit I did not think about using Seek.

**Comment by crawshaw** [comment]
Because I forgot to push it weeks ago. Oops! Done.
